import { test,expect } from '@playwright/test';
test('public catalogue, fiche, panorama fallback and linked request',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.getByRole('heading',{level:1})).toBeVisible();
 await page.screenshot({path:'test-results/home-desktop.png',fullPage:true});
 await page.goto('/catalogue');await page.getByLabel('Rechercher',{exact:true}).fill('Forest');await page.getByRole('button',{name:'Filtrer',exact:true}).click();
 // The demo title does not include Forest; use the explicit type filter.
 await page.getByLabel('Rechercher',{exact:true}).fill('');await page.getByRole('combobox',{name:'Type',exact:true}).selectOption('demo');await page.getByRole('button',{name:'Filtrer',exact:true}).click();
 await page.getByRole('heading',{name:'Vos premiers pas en 360°'}).click();
 await expect(page.getByRole('heading',{name:'Alternative textuelle'})).toBeVisible();
 await page.getByRole('button',{name:'Explorer en 360°'}).click();
 await expect(page.getByRole('button',{name:'Recentrer',exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Demander une démonstration',exact:true}).click();
 await expect(page).toHaveURL(/fiche=demo360/);
 await page.getByLabel('Nom',{exact:true}).fill('Visiteur Test');await page.getByLabel('Adresse e-mail',{exact:true}).fill('visitor@example.test');
 await page.getByLabel('Parlez-nous de votre besoin').fill('Une séance de découverte pour notre école.');
 await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Envoyer ma demande'}).click();
 await expect(page.getByRole('heading',{name:'Votre demande est enregistrée.'})).toBeVisible();
 expect(errors).toEqual([]);
});
test('client signup, own requests, role restrictions and logout',async({page})=>{
 await page.goto('/inscription');await page.getByLabel('Nom',{exact:true}).fill('Client Browser');
 await page.getByLabel('Adresse e-mail').fill('client-browser@example.test');await page.getByLabel('Mot de passe',{exact:true}).fill('Browser-client-password-2026!');
 await page.getByRole('button',{name:'Créer mon compte'}).click();await expect(page).toHaveURL('/dashboard');
 await expect(page.getByRole('navigation',{name:'Navigation de mon espace'}).getByRole('link',{name:'Utilisateurs'})).toHaveCount(0);
 const response=await page.request.get('/api/admin/users');expect(response.status()).toBe(403);
 await page.goto('/contact');await page.getByLabel('Nom',{exact:true}).fill('Client Browser');await page.getByLabel('Adresse e-mail').fill('client-browser@example.test');
 await page.getByLabel('Parlez-nous de votre besoin').fill('Demande liée à mon compte pour le test.');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Envoyer ma demande'}).click();
 await expect(page.getByRole('heading',{name:'Votre demande est enregistrée.'})).toBeVisible();
 await page.goto('/dashboard?tab=requests');await expect(page.getByText('Demande liée à mon compte pour le test.',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Se déconnecter'}).click();await expect(page).toHaveURL('/connexion');
 await page.goto('/dashboard');await expect(page).toHaveURL('/connexion');
});
test('admin creates, submits, publishes and archives a project',async({page})=>{
 await page.goto('/connexion');await page.getByLabel('Adresse e-mail').fill('admin@visuaa.test');await page.getByLabel('Mot de passe',{exact:true}).fill('Browser-test-password-2026!');
 await page.getByRole('button',{name:'Se connecter'}).click();await expect(page).toHaveURL('/dashboard');
 await page.screenshot({path:'test-results/dashboard-desktop.png',fullPage:true});
 await expect(page.locator('header.header,footer')).toHaveCount(0);
 await page.getByRole('link',{name:'Fiches du catalogue',exact:true}).click();await page.getByRole('button',{name:'Créer une fiche',exact:true}).click();
 await page.getByLabel('Titre',{exact:true}).fill('Texte à conserver');
 page.once('dialog',dialog=>dialog.dismiss());await page.getByRole('button',{name:'Fermer',exact:true}).click();
 await expect(page.getByLabel('Titre',{exact:true})).toHaveValue('Texte à conserver');
 page.once('dialog',dialog=>dialog.dismiss());await page.getByRole('link',{name:'Vue d’ensemble',exact:true}).click();
 await expect(page.getByLabel('Titre',{exact:true})).toHaveValue('Texte à conserver');
 await page.getByLabel('Titre',{exact:true}).fill('Projet navigateur');await page.getByLabel('Adresse de la fiche').fill('projet-navigateur');
 await page.getByRole('combobox',{name:'Type',exact:true}).selectOption('projet');await page.getByLabel('Secteur',{exact:true}).fill('Éducation');
 await page.getByLabel('Résumé',{exact:true}).fill('Une présentation du projet de découverte.');
 await page.getByLabel('Contenu',{exact:true}).fill('Ce projet permet de vérifier le parcours de création et de publication depuis le navigateur.');
 await page.getByRole('combobox',{name:'État',exact:true}).selectOption('review');await page.getByRole('button',{name:'Enregistrer la fiche',exact:true}).click();
 await expect(page.locator('.admin-msg')).toContainText('Fiche enregistrée');
 await page.getByRole('combobox',{name:'État',exact:true}).selectOption('verified');await page.getByRole('button',{name:'Enregistrer la fiche',exact:true}).click();await expect(page.getByRole('button',{name:'Enregistrer la fiche',exact:true})).toBeEnabled();
 await page.getByRole('combobox',{name:'État',exact:true}).selectOption('published');await page.getByRole('button',{name:'Enregistrer la fiche',exact:true}).click();
 await expect(page.getByRole('button',{name:'Enregistrer la fiche',exact:true})).toBeEnabled();
 await expect.poll(async()=> (await page.request.get('/experiences/projet-navigateur')).status()).toBe(200);
 await page.getByRole('combobox',{name:'État',exact:true}).selectOption('archived');await page.getByRole('button',{name:'Enregistrer la fiche',exact:true}).click();
 await expect(page.getByRole('button',{name:'Enregistrer la fiche',exact:true})).toBeEnabled();
 await expect.poll(async()=> (await page.request.get('/experiences/projet-navigateur')).status()).toBe(404);
});
test('mobile navigation, filters, language and public SEO',async({page,request})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');
 await page.getByRole('button',{name:'Ouvrir le menu'}).click();await page.getByRole('dialog').getByRole('link',{name:'Catalogue',exact:true}).click();
 await page.getByRole('combobox',{name:'Domaine',exact:true}).selectOption('agriculture');await page.getByRole('button',{name:'Filtrer',exact:true}).click();await expect(page.getByRole('status')).toContainText('50');
 await page.getByRole('link',{name:'English',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('lang','en');await expect(page).toHaveURL(/domaine=agriculture/);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'test-results/catalogue-mobile.png',fullPage:true});
 const robots=await request.get('/robots.txt');expect(await robots.text()).toContain('Allow: /');
 const sitemap=await request.get('/sitemap.xml');expect(await sitemap.text()).toContain('/experiences/premiers-pas-en-360');
 const redirect=await request.get('/ancien-parcours',{maxRedirects:0});expect(redirect.status()).toBe(308);expect(redirect.headers().location).toContain('/catalogue');
 await page.goto('/experiences/premiers-pas-en-360?lang=fr');await expect(page.locator('link[rel=canonical]')).toHaveAttribute('href','http://127.0.0.1:3100/experiences/premiers-pas-en-360');
 await expect(page.locator('script[type="application/ld+json"]')).toHaveCount(1);
});
