import Image from 'next/image';
import {pageMetadata} from '@/lib/seo';
import {translateNode} from '@/lib/i18n/tree';
import {getLocale} from '@/lib/i18n/server';

import {DiscoveryGallery} from '@/components/discovery-gallery';
import Link from '@/components/site-link';
import {ArrowUpRight,ArrowDown,Pickaxe,Compass,Users,Clapperboard,Headset} from 'lucide-react';
export async function generateMetadata(){return pageMetadata('/qui-sommes-nous',"À propos","Découvrez VISUAA, une plateforme pour mieux connaître les métiers et les territoires de la RDC.",await getLocale())}
export default async function Page(){const locale=await getLocale();return translateNode(<main id="main" className="page-main about-page"><section className="catalogue-hero" aria-labelledby="about-title">
 <Image className="catalogue-hero-image" src="/images/kinshasa.webp" alt="Kinshasa et ses espaces verts, en République démocratique du Congo" fill sizes="(max-width: 1440px) 88vw, 1262px" preload/>
 <div className="catalogue-hero-shade" aria-hidden="true"/>
 <div className="catalogue-hero-copy">
 <span className="eyebrow">VISUA · CRÉATION & IMMERSION EN RDC</span>
 <h1 id="about-title">À propos de VISUA<br/><em>Depuis Kinshasa, ouvrir de nouveaux horizons.</em></h1>
 <p>Nous donnons une nouvelle dimension à la découverte.</p>
 <Link className="btn catalogue-hero-action" href="#notre-mission">NOTRE MISSION<ArrowDown size={18} aria-hidden="true"/></Link>
 </div>
 <p className="catalogue-hero-credit"><Link href="/credits">Photo : Irene2005 · CC BY 2.0</Link></p>
 </section>
 <div className="about-introduction"><p>VISUA est une entreprise créative et technologique en République démocratique du Congo, consacrée aux expériences immersives en réalité virtuelle et en vidéo 360°. Depuis Kinshasa, nous portons une ambition : rapprocher les publics des métiers, des territoires et des savoir-faire du pays.</p></div>
 <section id="notre-mission" className="about-mission"><span className="eyebrow">NOTRE MISSION</span><h2>Rendre la découverte plus accessible,<br/>plus vivante, plus concrète.</h2><p>Nous souhaitons démocratiser les usages de l’immersion en RDC, au service de l’éducation, de l’orientation professionnelle et de la valorisation du patrimoine. Jeunes, étudiants, entrepreneurs, écoles et organisations peuvent commencer leur découverte sur un écran, puis approfondir l’expérience lorsque les contenus immersifs sont disponibles.</p></section><section className="about-universes"><article><Pickaxe size={32}/><h2>Comprendre les métiers</h2><p>Mettre en lumière les missions, les environnements de travail et les compétences, dans les mines, l’agriculture, le tourisme et l’environnement. Aider chacun à se projeter et à mieux comprendre les activités qui façonnent le pays.</p><Link className="under-link" href="/metiers">Découvrir les métiers <ArrowUpRight size={18}/></Link></article><article><Compass size={32}/><h2>Explorer les territoires</h2><p>Faire connaître les paysages, la biodiversité, la culture et le patrimoine de la RDC. CongoVR invite à porter un nouveau regard sur les lieux et les histoires qui composent le pays.</p><Link className="under-link" href="/destinations">Explorer les destinations <ArrowUpRight size={18}/></Link></article></section><DiscoveryGallery/><section className="about-method"><span className="eyebrow">NOTRE DÉMARCHE</span><h2>Une expérience se construit ensemble.</h2><div className="about-method-grid"><article><Users size={26}/><h3>Comprendre votre public</h3><p>Partir de vos objectifs, de vos publics et du contexte de découverte.</p></article><article><Clapperboard size={26}/><h3>Préparer les contenus</h3><p>Documenter les sujets, écrire les parcours et préparer les autorisations nécessaires aux captations.</p></article><article><Headset size={26}/><h3>Accompagner l’immersion</h3><p>Adapter la présentation aux écrans et aux casques, avec une attention au confort et à l’accessibilité.</p></article></div></section><div className="catalogue-note"><div><h3>Un métier à faire découvrir ? Un territoire à valoriser ?</h3><p>Parlons de votre idée et des personnes auxquelles vous souhaitez la faire vivre.</p></div><Link className="btn dark" href="/contact">Construisons votre projet <ArrowUpRight size={18}/></Link></div><p className="about-reference small">Les fiches du catalogue indiquent leurs références et le type de contenu disponible. <Link href="/credits">Consulter les crédits et la provenance des contenus.</Link></p></main>,locale)}
