import { randomUUID,randomBytes } from 'node:crypto';
import { spawn } from 'node:child_process';
import { resolve } from 'node:path';
import { mkdirSync } from 'node:fs';
Object.assign(process.env,{NODE_ENV:'development'});
process.env.VISUA_TEST_DATABASE=resolve('.local-db','e2e-'+randomUUID());
process.env.SITE_URL='http://127.0.0.1:3100';
process.env.SITE_PUBLIC='true';
process.env.AUTH_SECRET=randomBytes(32).toString('hex');
process.env.ADMIN_EMAILS='admin@visuaa.test';
mkdirSync(process.env.VISUA_TEST_DATABASE,{recursive:true});
const {migrate}=await import('./migration-runner');
const {seedContent}=await import('../db/repository');
const {seed}=await import('../lib/seed');
const {provisionUser}=await import('../lib/auth');
const {database}=await import('../db/client');
await migrate();await seedContent(seed);
await provisionUser('admin@visuaa.test','Admin Test','admin','Browser-test-password-2026!');
const {defaultSettings}=await import('../lib/settings');
await (await database()).query("INSERT INTO settings(key,value) VALUES ('site',$1)",[JSON.stringify({...defaultSettings,redirects:[{source:'/ancien-parcours',destination:'/catalogue'}]})]);
await (await database()).close();
const server=spawn(process.execPath,['node_modules/next/dist/bin/next','dev','--hostname','127.0.0.1','--port','3100'],{stdio:'inherit',env:process.env,windowsHide:true});
for(const signal of ['SIGINT','SIGTERM'] as const)process.on(signal,()=>{server.kill(signal);process.exit()});
server.on('exit',code=>process.exit(code||0));
