import type {Experience} from './models';
import additional from './additional-careers.json' with {type:'json'};
import {domainOf} from './catalogue-metadata';
export type CatalogueGroup={id:string;label:string;title:string;description:string};
export const miningGroups:CatalogueGroup[]=[
{id:'exploration',label:'Exploration',title:'Lire le sous-sol et comprendre le gisement',description:'Du terrain au modèle géologique : observer, mesurer, échantillonner et interpréter.'},
{id:'extraction',label:'Extraction',title:'Organiser et conduire l’extraction',description:'Préparer les opérations, utiliser les engins et coordonner le travail sur le site.'},
{id:'traitement',label:'Traitement du minerai',title:'Du minerai à la matière valorisée',description:'Comprendre les procédés, conduire les installations et contrôler la qualité.'},
{id:'maintenance',label:'Maintenance & énergie',title:'Faire fonctionner les équipements',description:'Mécanique, électricité, automatisme : entretenir, diagnostiquer et fiabiliser.'},
{id:'securite',label:'Sécurité & environnement',title:'Prévenir les risques et suivre les impacts',description:'Protéger les équipes, surveiller l’eau et les milieux, accompagner la remise en état.'},
{id:'logistique',label:'Logistique & encadrement',title:'Relier les équipes et les opérations',description:'Approvisionnements, stocks, transport et coordination au service de l’activité minière.'}
];
export const destinationGroups:CatalogueGroup[]=[{"id": "parcs-reserves", "label": "Parcs et réserves", "title": "Parcs et réserves", "description": "Forêts, savanes et biodiversité : découvrez les grands milieux naturels présentés par l’ANAPI."}, {"id": "jardins", "label": "Jardins botaniques", "title": "Jardins botaniques", "description": "À Kinshasa, Kisantu et Eala, une rencontre avec les collections végétales et leur histoire."}, {"id": "eaux-paysages", "label": "Eaux et paysages", "title": "Eaux et paysages", "description": "L’eau dessine les paysages : cascades, rivières et mondes souterrains."}, {"id": "culture-musees", "label": "Culture et musées", "title": "Culture et musées", "description": "Des collections, des arts et des lieux de transmission au cœur de la capitale."}, {"id": "patrimoine", "label": "Villes et patrimoine", "title": "Villes et patrimoine", "description": "Stades, monuments, ouvrages d’art et arbres historiques racontent les villes congolaises."}];
export function categoryOf(e:Experience){return e.category||(e.kind==='metier'&&e.sector==='Mines & géosciences'?'exploration':e.kind==='destination'&&e.id==='kinshasa'?'culture':e.sector)}
export function catalogueGroups(kind:string,items:Experience[]):CatalogueGroup[]{const all:CatalogueGroup={id:'all',label:kind==='metier'?'Tous les métiers':kind==='destination'?'Toutes les destinations':'Tout explorer',title:kind==='metier'?'Les métiers à chaque étape de la mine':kind==='destination'?'Un pays, plusieurs horizons':'Toutes les découvertes',description:kind==='metier'?'Choisissez une famille pour découvrir les missions, les environnements de travail et les savoir-faire.':kind==='destination'?'Retrouvez les lieux documentés par l’ANAPI et leurs principaux repères.':'Des fiches à lire et un panorama pour découvrir la navigation 360°.'};const known=kind==='metier'?miningGroups:kind==='destination'?destinationGroups:[...miningGroups,...destinationGroups];const used=new Set(items.map(categoryOf));return [all,...known.filter(g=>used.has(g.id)),...Array.from(used).filter(id=>!known.some(g=>g.id===id)).map(id=>({id,label:items.find(e=>categoryOf(e)===id)?.sector||id,title:items.find(e=>categoryOf(e)===id)?.sector||id,description:'Explorez les fiches de cet univers.'}))]}

export function careerGroups(items:Experience[],domain:string){const subset=items.filter(e=>domain==='all'||domainOf(e)===domain);const ids=new Set(subset.map(categoryOf));const known=[...miningGroups,...additional.groups.map(g=>({...g,title:g.label}))];return [...known.filter(g=>ids.has(g.id)),...Array.from(ids).filter(id=>!known.some(g=>g.id===id)).map(id=>({id,label:subset.find(e=>categoryOf(e)===id)?.sector||id,title:id,description:''}))]}
