import DashboardIcon from './dashboard-icon';
export type AdminSummary={states:Record<string,number>;newRequests:number;activeUsers:number;media:number;recent:{id:string;title:string;status:string;updated_at:string}[]};
const states=[['draft','Brouillons'],['review','À vérifier'],['verified','Prêtes à publier'],['published','Publiées'],['archived','Archivées']];
export default function AdminOverview({data}:{data:AdminSummary}){
 return <div className="admin-overview"><div className="admin-quick-actions"><a className="btn dark" href="/dashboard?tab=contents&action=create"><DashboardIcon name="create"/>Créer une fiche</a><a className="btn outline" href="/dashboard?tab=requests&status=new"><DashboardIcon name="requests"/>Traiter les demandes <span>{data.newRequests}</span></a><a className="btn outline" href="/dashboard?tab=users"><DashboardIcon name="access"/>Gérer les accès</a></div>
 <section className="dashboard-box"><div className="panel-heading"><div><h2><DashboardIcon name="contents"/>Le catalogue en un regard</h2><p>Accédez aux fiches à chaque étape de publication.</p></div><a href="/dashboard?tab=contents">Toutes les fiches ↗</a></div><div className="workflow-grid">{states.map(([id,label])=><a href={'/dashboard?tab=contents&status='+id} key={id}><DashboardIcon name={id}/><strong>{data.states[id]||0}</strong><span>{label}</span></a>)}</div></section>
 <div className="overview-columns"><section className="dashboard-box"><h2><DashboardIcon name="priorities"/>Vos priorités</h2><a className="priority-row" href="/dashboard?tab=requests&status=new"><span>Demandes à contacter</span><strong>{data.newRequests}</strong></a><a className="priority-row" href="/dashboard?tab=contents&status=review"><span>Fiches à vérifier</span><strong>{data.states.review||0}</strong></a><a className="priority-row" href="/dashboard?tab=contents&status=verified"><span>Fiches prêtes à publier</span><strong>{data.states.verified||0}</strong></a><p className="small">Les droits, les textes et les médias restent à vérifier avant toute publication.</p></section>
 <section className="dashboard-box"><h2><DashboardIcon name="settings"/>Administration du site</h2><a className="priority-row" href="/dashboard?tab=media"><span>Images, vidéos et panoramas</span><strong>{data.media}</strong></a><a className="priority-row" href="/dashboard?tab=users"><span>Comptes actifs</span><strong>{data.activeUsers}</strong></a><a className="priority-row" href="/dashboard?tab=settings">Marque, référencement et redirections <span>↗</span></a><a className="priority-row" href="/dashboard?tab=audit">Consulter le journal d’activité <span>↗</span></a></section></div>
 <section className="dashboard-box"><h2><DashboardIcon name="audit"/>Dernières fiches modifiées</h2><div className="recent-content">{data.recent.map(e=><a key={e.id} href={'/dashboard?tab=contents&fiche='+e.id}><span><strong>{e.title}</strong><small>{states.find(([id])=>id===e.status)?.[1]||e.status}</small></span><time>{new Date(e.updated_at).toLocaleDateString('fr-FR')}</time></a>)}</div>{!data.recent.length&&<p>Aucune fiche pour le moment.</p>}</section></div>;
}
