'use client';
import SafeForm from '@/components/safe-form';
import { useEffect,useState } from 'react';
import type { User } from '@/lib/permissions';
import type { Lead } from '@/lib/models';
import type { SiteSettings } from '@/lib/settings';
import DashboardIcon from './dashboard-icon';
import AdminOverview,{type AdminSummary} from './admin-overview';
import ContentPanel from '../admin/panel';
type PageData<T>={items:T[];total:number;page:number;pageSize:number};
async function api<T>(url:string,method='GET',body?:unknown):Promise<T>{
 const r=await fetch(url,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'Action impossible.');return d;
}
function usePage<T>(url:string){
 const [page,setPage]=useState(1),[data,setData]=useState<PageData<T>|null>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
 useEffect(()=>{let alive=true;setData(null);api<PageData<T>>(url+(url.includes('?')?'&':'?')+'page='+page).then(d=>{if(alive){setData(d);setError('')}}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[url,page,refresh]);
 return {data,error,setError,page,setPage,reload:()=>setRefresh(n=>n+1)};
}
function Pagination({data,page,setPage}:{data:PageData<unknown>|null;page:number;setPage:(n:number)=>void}){return data?<nav className="pagination" aria-label="Pagination"><button disabled={page===1} onClick={()=>setPage(page-1)}>Précédent</button><span>Page {page} · {data.total} résultats</span><button disabled={page*data.pageSize>=data.total} onClick={()=>setPage(page+1)}>Suivant</button></nav>:null}
function RequestsPanel({role,initialStatus=''}:{role:string;initialStatus?:string}){
 const [status,setStatus]=useState(initialStatus);
 const p=usePage<Lead>('/api/admin/demandes?status='+encodeURIComponent(status)),[busy,setBusy]=useState(false);
 async function change(id:string,status:string){if(status==='deleted'&&!confirm('Supprimer définitivement les coordonnées et le message de cette demande ?'))return;setBusy(true);try{await api('/api/admin/demandes','PATCH',{id,status});p.reload()}catch(e){p.setError(e instanceof Error?e.message:'Erreur.')}finally{setBusy(false)}}
 return <section><h2>{role==='viewer'?'Mes demandes':'Demandes de démonstration'}</h2><p>{role==='editor'?'Demandes liées aux fiches dont vous êtes l’auteur.':role==='viewer'?'Seules les demandes envoyées pendant votre connexion apparaissent ici.':'Suivez les contacts reçus. Les notifications e-mail ne sont pas activées.'}</p>{p.error&&<p role="alert" className="error-message">{p.error}</p>}
 {!p.data&&!p.error&&<p role="status">Chargement…</p>}{p.data?.items.length===0&&<div className="notice">Aucune demande pour le moment. <a href="/contact">Préparer une démonstration</a></div>}
 <label className="dashboard-search">Filtrer les demandes<select value={status} onChange={e=>{setStatus(e.target.value);p.setPage(1)}}><option value="">Tous les statuts</option><option value="new">Nouvelles</option><option value="contacted">Contactées</option><option value="quoted">Devis</option><option value="closed">Clôturées</option></select></label><div className="request-list">{p.data?.items.map(l=><article className="request-card" key={l.id}><div className="panel-heading"><strong>{l.name}</strong><span className="pill">{{new:"Nouvelle",contacted:"Contactée",quoted:"Devis",closed:"Clôturée"}[l.status]||l.status}</span></div><p>{l.organization} · <a href={'mailto:'+l.email}>{l.email}</a></p><p className="request-message">{l.message}</p><p className="small">VIS-{l.id.slice(0,8).toUpperCase()} · {new Date(l.created_at).toLocaleDateString('fr-FR')} · {l.intent}</p>
 {role==='admin'&&<div className="admin-toolbar"><label>Statut<select aria-label={'Statut de la demande de '+l.name} disabled={busy} value={l.status} onChange={e=>void change(l.id,e.target.value)}>{[['new','Nouvelle'],['contacted','Contactée'],['quoted','Devis'],['closed','Clôturée']].map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><button className="btn danger" disabled={busy} onClick={()=>void change(l.id,'deleted')}>Supprimer les données</button></div>}</article>)}</div><Pagination {...p}/></section>;
}
function UsersPanel(){
 const p=usePage<User>('/api/admin/users'),[selected,setSelected]=useState<User|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);try{await api('/api/admin/users','POST',Object.fromEntries(new FormData(form)));form.reset();setMessage('Compte créé. Transmettez les accès par un canal sûr.');p.reload()}catch(e){p.setError(e instanceof Error?e.message:'Erreur.')}finally{setBusy(false)}}
 async function update(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const data=Object.fromEntries(new FormData(e.currentTarget));if(!data.password)delete data.password;setBusy(true);try{await api('/api/admin/users','PATCH',{...data,id:selected.id});setSelected(null);setMessage('Compte mis à jour ; ses sessions ont été révoquées.');p.reload()}catch(e){p.setError(e instanceof Error?e.message:'Erreur.')}finally{setBusy(false)}}
 async function remove(id:string){if(!confirm('Supprimer ce compte et toutes ses demandes liées ?'))return;setBusy(true);try{await api('/api/admin/users','DELETE',{id});setSelected(null);p.reload()}catch(e){p.setError(e instanceof Error?e.message:'Erreur.')}finally{setBusy(false)}}
 return <section><h2>Utilisateurs et rôles</h2>{p.error&&<p role="alert" className="error-message">{p.error}</p>}{message&&<p role="status">{message}</p>}
 <SafeForm className="form-card" onSubmit={create}><h3>Créer un compte</h3><div className="form-row"><label>Nom<input name="name" required minLength={2} maxLength={100}/></label><label>E-mail<input name="email" type="email" required/></label></div><div className="form-row"><label>Mot de passe initial<input name="password" type="password" required minLength={12} maxLength={128} autoComplete="new-password"/></label><label>Rôle<select name="role"><option value="viewer">Client / consultation</option><option value="editor">Éditeur</option><option value="admin">Administrateur</option></select></label></div><button className="btn dark" disabled={busy}>Créer le compte</button></SafeForm>
 <div className="admin-list">{p.data?.items.map(u=><article className="admin-item" key={u.id}><div><strong>{u.name}</strong><p>{u.email} · {u.role} · {u.status}</p></div><button className="btn outline" onClick={()=>setSelected(u)}>Gérer</button></article>)}</div><Pagination {...p}/>
 {selected&&<SafeForm className="form-card" onSubmit={update} key={selected.id}><h3>Gérer {selected.name}</h3><label>Rôle<select name="role" defaultValue={selected.role}>{['admin','editor','viewer'].map(r=><option key={r}>{r}</option>)}</select></label><label>Statut<select name="status" defaultValue={selected.status}><option value="active">Actif</option><option value="disabled">Désactivé</option></select></label><label>Nouveau mot de passe (facultatif)<input name="password" type="password" minLength={12} maxLength={128} autoComplete="new-password"/></label><div className="admin-toolbar"><button className="btn dark" disabled={busy}>Enregistrer le compte</button><button type="button" className="btn danger" disabled={busy} onClick={()=>void remove(selected.id)}>Supprimer le compte</button><button type="button" onClick={()=>setSelected(null)}>Fermer</button></div></SafeForm>}
 </section>;
}
function SettingsPanel(){
 const [value,setValue]=useState<SiteSettings|null>(null),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{api<SiteSettings>('/api/admin/settings').then(setValue).catch(e=>setError(e.message))},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('/api/admin/settings','PUT',value);setMessage('Paramètres enregistrés.')}catch(e){setError(e instanceof Error?e.message:'Erreur.')}finally{setBusy(false)}}
 return <section><h2>Paramètres du site</h2>{error&&<p role="alert" className="error-message">{error}</p>}{message&&<p role="status">{message}</p>}{value&&<SafeForm className="editor" onSubmit={save}><label>Nom de marque<input required maxLength={40} value={value.brand} onChange={e=>setValue({...value,brand:e.target.value})}/></label><label>Titre SEO par défaut<input required maxLength={120} value={value.seoTitle} onChange={e=>setValue({...value,seoTitle:e.target.value})}/></label><label>Description SEO par défaut<textarea required minLength={20} maxLength={300} value={value.seoDescription} onChange={e=>setValue({...value,seoDescription:e.target.value})}/></label>
 <h3>Redirections des anciennes pages</h3><p>Associez un ancien chemin à une page publique existante. Le domaine et l’ouverture publique sont configurés dans l’environnement de déploiement.</p>
 {value.redirects.map((r,i)=><div className="point-editor" key={i}><label>Ancien chemin<input required placeholder="/ancienne-page" value={r.source} onChange={e=>setValue({...value,redirects:value.redirects.map((x,j)=>i===j?{...x,source:e.target.value}:x)})}/></label><label>Destination<input required placeholder="/catalogue" value={r.destination} onChange={e=>setValue({...value,redirects:value.redirects.map((x,j)=>i===j?{...x,destination:e.target.value}:x)})}/></label><button type="button" onClick={()=>setValue({...value,redirects:value.redirects.filter((_,j)=>i!==j)})}>Retirer</button></div>)}
 <div className="admin-toolbar"><button type="button" onClick={()=>setValue({...value,redirects:[...value.redirects,{source:'',destination:'/catalogue'}]})}>Ajouter une redirection</button><button className="btn dark" disabled={busy}>Enregistrer les paramètres</button></div></SafeForm>}</section>;
}
function AuditPanel(){
 const p=usePage<{id:string;user_id:string|null;action:string;target:string;created_at:string}>('/api/admin/audit');
 return <section><h2>Journal d’activité</h2>{p.error&&<p role="alert">{p.error}</p>}<div className="table-scroll"><table><thead><tr><th>Date</th><th>Action</th><th>Cible</th><th>Acteur</th></tr></thead><tbody>{p.data?.items.map(a=><tr key={a.id}><td>{new Date(a.created_at).toLocaleString('fr-FR')}</td><td>{a.action}</td><td>{a.target}</td><td>{a.user_id||'Compte supprimé'}</td></tr>)}</tbody></table></div><Pagination {...p}/></section>;
}
function AccountPanel(){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{await api('/api/auth/password','POST',Object.fromEntries(new FormData(e.currentTarget)));location.assign('/connexion')}catch(e){setError(e instanceof Error?e.message:'Erreur.');setBusy(false)}}
 return <section><h2>Mon compte</h2><SafeForm className="form-card" onSubmit={submit}><label>Mot de passe actuel<input name="current" type="password" required autoComplete="current-password"/></label><label>Nouveau mot de passe<input name="password" type="password" required minLength={12} maxLength={128} autoComplete="new-password"/></label>{error&&<p role="alert">{error}</p>}<p>Ce changement déconnecte toutes vos sessions.</p><button className="btn dark" disabled={busy}>Changer mon mot de passe</button></SafeForm></section>;
}
export default function Dashboard({user,tab,stats,summary,filters={}}:{user:User;tab:string;stats:{content:number;requests:number;users:number|null};summary?:AdminSummary;filters?:{status?:string;action?:string;fiche?:string}}){
 const [error,setError]=useState('');
 const links=[['overview','Vue d’ensemble'],...(user.role!=='viewer'?[['contents','Fiches du catalogue'],['media','Médias et panoramas']]:[]),['requests',user.role==='viewer'?'Mes demandes':'Demandes'],...(user.role==='admin'?[['users','Utilisateurs'],['settings','Paramètres'],['audit','Journal d’activité']]:[]),['account','Mon compte']];
 const active=links.some(([id])=>id===tab)?tab:'overview';
 async function logout(){try{await api('/api/auth/logout','POST',{});location.assign('/connexion')}catch(e){setError(e instanceof Error?e.message:'Déconnexion impossible.')}}
 return <main id="main" className="workspace"><aside className="workspace-nav"><a className="workspace-brand" href="/dashboard">VISUA<span>Administration & suivi</span></a><span className="eyebrow">ESPACE {user.role==='admin'?'ADMINISTRATEUR':user.role==='editor'?'ÉDITEUR':'CLIENT'}</span><strong>{user.name}</strong><nav aria-label="Navigation de mon espace">{links.map(([id,label])=><a key={id} href={'/dashboard?tab='+id} aria-current={active===id?'page':undefined}><DashboardIcon name={id}/>{label}</a>)}</nav><a className="workspace-site-link" href="/" target="_blank" rel="noreferrer"><DashboardIcon name="external"/>Ouvrir le site</a><a href="/catalogue" target="_blank" rel="noreferrer"><DashboardIcon name="contents"/>Voir le catalogue</a><button onClick={()=>void logout()}><DashboardIcon name="logout"/>Se déconnecter</button>{error&&<p role="alert">{error}</p>}</aside>
 <div className="workspace-content"><div className="workspace-topbar"><span><DashboardIcon name={active}/>{links.find(([id])=>id===active)?.[1]}</span><div><span className="pill">{user.role==='admin'?'Administrateur':user.role==='editor'?'Éditeur':'Client'}</span><a href="/dashboard?tab=account">{user.email}</a></div></div>{active==='overview'?<><span className="eyebrow">VOTRE ACTIVITÉ</span><h1>Bonjour {user.name}.</h1><p>Retrouvez vos contenus, vos demandes et les prochaines actions.</p><div className="stats-grid"><a href={user.role==='viewer'?'/catalogue':'/dashboard?tab=contents'}><DashboardIcon name="contents"/><strong>{stats.content}</strong><span>Fiches {user.role==='viewer'?'publiées':'de l’équipe'}</span></a><a href="/dashboard?tab=requests"><DashboardIcon name="requests"/><strong>{stats.requests}</strong><span>Demandes accessibles</span></a>{stats.users!==null&&<a href="/dashboard?tab=users"><DashboardIcon name="users"/><strong>{stats.users}</strong><span>Utilisateurs</span></a>}</div>{summary?<AdminOverview data={summary}/>:<div className="notice"><h2>{user.role==='viewer'?'Prochaine découverte':'Construire la suite'}</h2><p>{user.role==='viewer'?'Explorez le catalogue puis demandez une démonstration adaptée à votre public.':'Créez une fiche, vérifiez les droits des médias et soumettez le contenu avant sa publication.'}</p><a className="btn dark" href={user.role==='viewer'?'/catalogue':'/dashboard?tab=contents'}>{user.role==='viewer'?'Explorer le catalogue':'Gérer les fiches'}</a></div>}</>:active==='contents'||active==='media'?<ContentPanel key={active} userRole={user.role} userId={user.id} initialStatus={filters.status} initialCreate={filters.action==='create'} initialId={filters.fiche} mediaOnly={active==='media'}/>:active==='requests'?<RequestsPanel role={user.role} initialStatus={filters.status}/>:active==='users'?<UsersPanel/>:active==='settings'?<SettingsPanel/>:active==='audit'?<AuditPanel/>:<AccountPanel/>}</div></main>;
}
