import assert from 'node:assert/strict';import {test} from 'node:test';import {createElement} from 'react';import {readFileSync} from 'node:fs';
import {resolveLocale,languageHref} from '../lib/i18n/locale.ts';import {t,localizeMetadata} from '../lib/i18n/text.ts';import {translateNode} from '../lib/i18n/tree.ts';import {seed} from '../lib/seed.ts';import {searchText} from '../lib/catalogue-metadata.ts';
const dictionary=JSON.parse(readFileSync(new URL('../lib/i18n/en.json',import.meta.url),'utf8'));
await test('supported language selection has explicit precedence and safe fallback',()=>{assert.equal(resolveLocale('en','fr'),'en');assert.equal(resolveLocale('fr','en'),'fr');assert.equal(resolveLocale(null,'en'),'en');assert.equal(resolveLocale('de','en'),'en');assert.equal(resolveLocale('<script>','bad'),'fr')});
await test('language navigation preserves province, family and anchors without rewriting external URLs',()=>{const u=new URL(languageHref('/destinations?province=Kongo+Central&famille=parcs-reserves#main','en'),'https://test.local');assert.equal(u.searchParams.get('province'),'Kongo Central');assert.equal(u.searchParams.get('famille'),'parcs-reserves');assert.equal(u.searchParams.get('lang'),'en');assert.equal(u.hash,'#main');assert.equal(languageHref('https://example.org','en'),'https://example.org');assert.equal(languageHref('/documents/anapi-tourisme.pdf#page=3','en'),'/documents/anapi-tourisme.pdf#page=3');assert.equal(languageHref('/api/demandes','en'),'/api/demandes');assert.equal(languageHref('//example.org','en'),'//example.org')});
await test('all existing career and destination titles, descriptions and paragraphs have English translations',()=>{for(const e of seed){for(const s of [e.title,e.description,e.body,...e.body.split(/\n\s*\n/),...e.skills,e.provinceNote||''].filter(Boolean)){assert.ok(Object.hasOwn(dictionary,s),e.id+': '+s.slice(0,80));assert.ok(t(s,'en').trim());assert.equal(t(s,'fr'),s)}}});
await test('React translation preserves handlers, ids, field values and canonical filter values',()=>{const onClick=()=>42;const original=createElement('button',{id:'fr-id',onClick,value:'metier','aria-label':'Les métiers'},createElement('span',null,'Les métiers'));const en=translateNode(original,'en');assert.equal(en.props.onClick,onClick);assert.equal(en.props.value,'metier');assert.equal(en.props.id,'fr-id');assert.equal(en.props['aria-label'],t('Les métiers','en'));assert.equal(en.props.children.props.children,t('Les métiers','en'));assert.equal(translateNode(original,'fr'),original);const input=translateNode(createElement('input',{value:'Les métiers',placeholder:'Les métiers'}),'en');assert.equal(input.props.value,'Les métiers');assert.equal(input.props.placeholder,t('Les métiers','en'));const link=translateNode(createElement('a',{href:'/metiers?domaine=agriculture'},'Les métiers'),'en');assert.equal(link.props.href,'/metiers?domaine=agriculture&lang=en')});
await test('metadata is translated while icon and resource URLs remain intact',()=>{const meta={title:{default:'Les métiers',template:'%s | VISUAA'},description:'Découvrez les métiers et les territoires de la RDC par les contenus immersifs et la vidéo 360°. Avec ou sans casque.',icons:{icon:'/favicon.svg'}};const en=localizeMetadata(meta,'en');assert.notEqual(en.title.default,meta.title.default);assert.notEqual(en.description,meta.description);assert.equal(en.icons.icon,meta.icons.icon);assert.equal(en.title.template,meta.title.template)});
await test('search matches English and French job titles using the same canonical record',()=>{const farmer=seed.find(e=>e.id==='agri-agriculteur-vivrier');assert.ok(searchText(farmer).includes('agriculteur'));assert.ok(searchText(farmer).includes('farmer'));assert.equal(t('2 min de lecture','en'),'2 min read');assert.equal(t('Culture et musées (3)','en'),t('Culture et musées','en')+' (3)')});
